### PR TITLE
fix: client.lua

### LINKED ISSUE #18: Issue entering trunk after placing others in and out of trunk.
By default you get the target option to enter the vehicle trunk. When you carry a player you are able to put them in the trunk, After you remove them and even uncarry them the option to hide yourself in the trunk doesn't appear anymore but yet i'm still able to place the other player in the trunk.

### PR DESCRIPTION
**Pull request by m1ch433l**
This should fix #18

### CODE REVIEW

**Review by TheCocoNutHead — COMMENTED** [review]
This hasn't fixed the issue and created even more problems, Now when a player is been carried they can't speak anymore until you release them and like 10 seconds pass. I'm also no longer able to place them in the trunk nor does the option to hide in the trunk my self appear.

**Comment by m1ch433l** [comment]
> This hasn't fixed the issue and created even more problems, Now when a player is been carried they can't speak anymore until you release them and like 10 seconds pass. I'm also no longer able to place them in the trunk nor does the option to hide in the trunk my self appear.

What was your previous version of this script? Im starting to think you had older. @s1nyx can you revert the PR? I will look into it later this day

**Comment by TheCocoNutHead** [comment]
Here is a clip
https://medal.tv/games/gta-v/clips/1OxscnzfWZgqI6/d1337tyDxXDf?invite=cr-MSxVdVYsMTEwMjAxMjk5LA

Il have to check this later today again what the version was.

**Comment by m1ch433l** [comment]
> Here is a clip https://medal.tv/games/gta-v/clips/1OxscnzfWZgqI6/d1337tyDxXDf?invite=cr-MSxVdVYsMTEwMjAxMjk5LA
> 
> Il have to check this later today again what the version was.

thanks for the clip. It’s very possible that you had version which was unfixed because when I started collaborating in this project I fixed issue like this but I’m not sure it is the same. 

Let me ask you. Did you have option to allow blackout in config?

**Comment by m1ch433l** [comment]
Oh I see in the end of the clip. So I made mistake somewhere

**Comment by s1nyx** [comment]
Revert done. @m1ch433l

**Comment by TheCocoNutHead** [comment]
This fixed?

**Comment by m1ch433l** [comment]
> This fixed?

Pushed new PR with fix ,wait for merge by @s1nyx

**Comment by s1nyx** [comment]
@TheCocoNutHead download the version 1.4.7

**Comment by TheCocoNutHead** [comment]
So far so good just found a new issue.

So you carry the player and place them in the trunk the STOP CARRY notification remains on screen and when you use the button the player gets removed from the trunk but is frozen and can't move. Until you place them in vehicle again and release them.

Maybe look so it removes that when the player has been placed in the trunk.
Also didnt test this but possibly reset for when example vehicle is deleted while player is trunk so they aren't stuck or frozen.

https://medal.tv/games/gta-v/clips/1PbilX31a0RdWi/d13371JTwcJg?invite=cr-MSxRejYsMTEwMjAxMjk5LA

**Comment by m1ch433l** [comment]
> So far so good just found a new issue.
> 
> So you carry the player and place them in the trunk the STOP CARRY notification remains on screen and when you use the button the player gets removed from the trunk but is frozen and can't move. Until you place them in vehicle again and release them.
> 
> Maybe look so it removes that when the player has been placed in the trunk. Also didnt test this but possibly reset for when example vehicle is deleted while player is trunk so they aren't stuck or frozen.
> 
> https://medal.tv/games/gta-v/clips/1PbilX31a0RdWi/d13371JTwcJg?invite=cr-MSxRejYsMTEwMjAxMjk5LA
I think it's easy just don't press that's all, but I'll look into it

**Comment by TheCocoNutHead** [comment]
> > So far so good just found a new issue.
> > So you carry the player and place them in the trunk the STOP CARRY notification remains on screen and when you use the button the player gets removed from the trunk but is frozen and can't move. Until you place them in vehicle again and release them.
> > Maybe look so it removes that when the player has been placed in the trunk. Also didnt test this but possibly reset for when example vehicle is deleted while player is trunk so they aren't stuck or frozen.
> > https://medal.tv/games/gta-v/clips/1PbilX31a0RdWi/d13371JTwcJg?invite=cr-MSxRejYsMTEwMjAxMjk5LA
> 
> I think it's easy just don't press that's all, but I'll look into it

Well downside of public server, You will have someone press it

**Comment by TheCocoNutHead** [comment]
> > So far so good just found a new issue.
> > So you carry the player and place them in the trunk the STOP CARRY notification remains on screen and when you use the button the player gets removed from the trunk but is frozen and can't move. Until you place them in vehicle again and release them.
> > Maybe look so it removes that when the player has been placed in the trunk. Also didnt test this but possibly reset for when example vehicle is deleted while player is trunk so they aren't stuck or frozen.
> > https://medal.tv/games/gta-v/clips/1PbilX31a0RdWi/d13371JTwcJg?invite=cr-MSxRejYsMTEwMjAxMjk5LA
> 
> I think it's easy just don't press that's all, but I'll look into it

Have there been any updates?

**Comment by s1nyx** [comment]
> > > So far so good just found a new issue.
> > > So you carry the player and place them in the trunk the STOP CARRY notification remains on screen and when you use the button the player gets removed from the trunk but is frozen and can't move. Until you place them in vehicle again and release them.
> > > Maybe look so it removes that when the player has been placed in the trunk. Also didnt test this but possibly reset for when example vehicle is deleted while player is trunk so they aren't stuck or frozen.
> > > https://medal.tv/games/gta-v/clips/1PbilX31a0RdWi/d13371JTwcJg?invite=cr-MSxRejYsMTEwMjAxMjk5LA
> > 
> > 
> > I think it's easy just don't press that's all, but I'll look into it
> 
> Have there been any updates?

Hey, 

No.
Please create an issue. Avoid commenting on PR merged.

Thanks and have a nice day.

**Pull request merged**
